#ifndef LVGL_H
#define LVGL_H

#ifdef __cplusplus
extern "C" {
#endif

// header file required to include lv_font.h in autogenerated font.c files

#include "lv_font.h"

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif /*LVGL_H*/
